import { useState, type FormEvent } from "react";
import { ArrowRight, Handshake, MapPin, Save, Search } from "lucide-react";
import type { Partner } from "../types";
import { DetailHeader, EmptyState, InfoGrid, PageHeader, StatusTag } from "../components/ui";

function PartnerEditor({ partner, onSave, onCancel }: { partner: Partner; onSave: (partner: Partner) => void; onCancel: () => void }) {
  const [draft, setDraft] = useState(partner);
  const submit = (event: FormEvent) => { event.preventDefault(); onSave(draft); };
  return <form className="edit-form" onSubmit={submit}><header><h2>编辑伙伴资料</h2><p>更新机构基础信息与合作状态。</p></header><div className="form-grid"><label><span>机构名称</span><input required maxLength={100} value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} /></label><label><span>伙伴类型</span><input required value={draft.type} onChange={(event) => setDraft({ ...draft, type: event.target.value })} /></label><label><span>所在地区</span><input required value={draft.city} onChange={(event) => setDraft({ ...draft, city: event.target.value })} /></label><label><span>合作状态</span><select value={draft.status} onChange={(event) => setDraft({ ...draft, status: event.target.value as Partner["status"] })}><option>优先合作</option><option>合作中</option><option>待接洽</option></select></label><label className="span-2"><span>机构简介</span><textarea rows={4} maxLength={240} value={draft.description} onChange={(event) => setDraft({ ...draft, description: event.target.value })} /></label></div><footer><button type="button" className="button secondary" onClick={onCancel}>取消</button><button className="button primary" type="submit"><Save size={16} />保存修改</button></footer></form>;
}

export function PartnersPage({ items, onItemsChange, notify }: { items: Partner[]; onItemsChange: (items: Partner[]) => void; notify: (message: string) => void }) {
  const [query, setQuery] = useState("");
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [editing, setEditing] = useState(false);
  const filtered = items.filter((partner) => `${partner.name}${partner.type}${partner.city}`.toLowerCase().includes(query.toLowerCase()));
  const selected = items.find((partner) => partner.id === selectedId);
  if (selected) return <div className="page detail-page"><DetailHeader title={selected.name} subtitle={`${selected.type} · ${selected.city}`} onBack={() => { setSelectedId(null); setEditing(false); }} onEdit={() => setEditing(true)} />{editing ? <PartnerEditor partner={selected} onCancel={() => setEditing(false)} onSave={(updated) => { onItemsChange(items.map((item) => item.id === updated.id ? updated : item)); setEditing(false); notify("伙伴资料已更新"); }} /> : <>
    <section className="entity-summary partner-hero"><div><span className="partner-logo large">{selected.name.slice(0, 2)}</span><div><StatusTag status={selected.status} /><h2>{selected.description}</h2><p><MapPin size={14} />{selected.city}</p></div></div><div className="priority-box"><span>合作优先级</span><strong>{selected.priority}</strong></div></section>
    <div className="detail-columns"><section className="detail-section"><header><h2>伙伴信息</h2></header><InfoGrid items={[["伙伴类型", selected.type], ["合作状态", selected.status], ["所在地区", selected.city], ["合作优先级", selected.priority]]} /></section><section className="detail-section"><header><h2>合作能力</h2><p>可用于融资场景与数据协同</p></header><ul className="service-list">{selected.services.map((service) => <li key={service}><span /><strong>{service}</strong></li>)}</ul></section></div>
    <section className="detail-section"><header><h2>建议合作路径</h2></header><div className="cooperation-steps"><div><span>1</span><strong>业务对接</strong><p>明确客群范围、数据授权和合作边界。</p></div><div><span>2</span><strong>规则映射</strong><p>把业务字段映射为可解释的产品准入条件。</p></div><div><span>3</span><strong>联合验证</strong><p>使用脱敏样本验证匹配质量与转化流程。</p></div></div></section></>}
  </div>;
  return <div className="page list-page"><PageHeader title="生态伙伴" description="管理资金、数据、场景与渠道伙伴的合作信息。" /><div className="partner-metrics"><div><strong>{items.length}</strong><span>已建档伙伴</span></div><div><strong>{items.filter((item) => item.status === "合作中").length}</strong><span>合作中</span></div><div><strong>{items.filter((item) => item.priority === "最高").length}</strong><span>最高优先级</span></div></div><div className="list-toolbar"><label className="search-control"><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索伙伴、类型或地区" /></label><span>共 {filtered.length} 家机构</span></div>{filtered.length ? <section className="partner-list">{filtered.map((partner) => <button key={partner.id} onClick={() => setSelectedId(partner.id)}><span className="partner-logo">{partner.name.slice(0, 2)}</span><div><small>{partner.type}</small><h2>{partner.name}</h2><p>{partner.description}</p><i><MapPin size={13} />{partner.city}</i></div><span className="partner-side"><StatusTag status={partner.status} /><b>{partner.priority}优先级</b><i>查看详情<ArrowRight size={14} /></i></span></button>)}</section> : <EmptyState title="未找到相关伙伴" description="请调整关键词后重试。" />}</div>;
}
