import { useMemo, useState, type FormEvent } from "react";
import { ArrowRight, Banknote, CheckCircle2, CircleAlert, PackageSearch, Save, Search } from "lucide-react";
import { runMatching } from "../matcher";
import type { ClientProfile, Product } from "../types";
import { DetailHeader, EmptyState, InfoGrid, PageHeader, StatusTag } from "../components/ui";

function ProductEditor({ product, onSave, onCancel }: { product: Product; onSave: (product: Product) => void; onCancel: () => void }) {
  const [draft, setDraft] = useState(product);
  const change = (key: keyof Product, value: string) => setDraft((current) => ({ ...current, [key]: value }));
  const submit = (event: FormEvent) => { event.preventDefault(); onSave(draft); };
  return <form className="edit-form" onSubmit={submit}><header><div><h2>编辑产品资料</h2><p>准入计算函数保持不变，仅更新展示信息。</p></div></header><div className="form-grid"><label><span>产品名称</span><input required maxLength={80} value={draft.name} onChange={(event) => change("name", event.target.value)} /></label><label><span>资金方</span><input required maxLength={80} value={draft.funder} onChange={(event) => change("funder", event.target.value)} /></label><label><span>目标客群</span><input required maxLength={100} value={draft.audience} onChange={(event) => change("audience", event.target.value)} /></label><label><span>额度范围</span><input required value={draft.amountLabel} onChange={(event) => change("amountLabel", event.target.value)} /></label><label><span>参考利率</span><input required value={draft.rateLabel} onChange={(event) => change("rateLabel", event.target.value)} /></label><label><span>期限</span><input required value={draft.termLabel} onChange={(event) => change("termLabel", event.target.value)} /></label></div><footer><button type="button" className="button secondary" onClick={onCancel}>取消</button><button className="button primary" type="submit"><Save size={16} />保存修改</button></footer></form>;
}

export function ProductsPage({ items, onItemsChange, currentClient, onMatch, notify }: { items: Product[]; onItemsChange: (items: Product[]) => void; currentClient: ClientProfile; onMatch: () => void; notify: (message: string) => void }) {
  const [query, setQuery] = useState("");
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [editing, setEditing] = useState(false);
  const filtered = items.filter((product) => `${product.name}${product.funder}${product.audience}`.toLowerCase().includes(query.toLowerCase()));
  const selected = items.find((product) => product.id === selectedId);
  const currentResult = useMemo(() => selected ? runMatching(currentClient, items).find((result) => result.product.id === selected.id) : undefined, [currentClient, items, selected]);
  if (selected) return <div className="page detail-page"><DetailHeader title={selected.name} subtitle={`${selected.funder} · ${selected.currency}`} onBack={() => { setSelectedId(null); setEditing(false); }} onEdit={() => setEditing(true)} />{editing ? <ProductEditor product={selected} onCancel={() => setEditing(false)} onSave={(updated) => { onItemsChange(items.map((item) => item.id === updated.id ? updated : item)); setEditing(false); notify("产品资料已更新"); }} /> : <>
    <section className="entity-summary product-hero"><div><span className="entity-icon"><Banknote size={19} /></span><div><h2>{selected.audience}</h2><p>{selected.source}</p></div></div>{currentResult ? <div className="current-fit"><span>当前客户匹配</span><strong>{currentResult.score}%</strong><StatusTag status={currentResult.status} /></div> : null}</section>
    <div className="detail-columns"><section className="detail-section"><header><h2>产品要素</h2></header><InfoGrid items={[["资金方", selected.funder], ["目标客群", selected.audience], ["额度范围", selected.amountLabel], ["参考利率", selected.rateLabel], ["融资期限", selected.termLabel], ["币种", selected.currency]]} /></section><section className="detail-section"><header><h2>当前客户判断</h2></header>{currentResult ? <ul className={currentResult.status === "可做" ? "reason-list success" : "reason-list danger"}>{(currentResult.status === "可做" ? currentResult.passes : currentResult.failures).map((reason) => <li key={reason}>{currentResult.status === "可做" ? <CheckCircle2 size={16} /> : <CircleAlert size={16} />}<span>{reason}</span></li>)}</ul> : null}<button className="button secondary full-button" onClick={onMatch}><PackageSearch size={16} />进入完整匹配</button></section></div>
    <section className="detail-section"><header><h2>申请材料</h2><p>提交前请按资金方最新口径复核</p></header><ol className="document-grid">{selected.materials.map((item, index) => <li key={item}><span>{String(index + 1).padStart(2, "0")}</span>{item}</li>)}</ol><p className="approval-note">产品信息仅用于业务初筛，以资金方最终审批为准。</p></section></>}
  </div>;
  return <div className="page list-page"><PageHeader title="产品中心" description="集中管理资金方产品要素、准入规则与材料要求。" /><div className="list-toolbar"><label className="search-control"><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索产品、资金方或目标客群" /></label><span>共 {filtered.length} 个产品</span></div>{filtered.length ? <section className="data-table product-management-table"><div className="table-head"><span>产品 / 资金方</span><span>目标客群</span><span>额度</span><span>年化利率</span><span>期限</span><span>币种</span><span>操作</span></div>{filtered.map((product) => <button className="table-row" key={product.id} onClick={() => setSelectedId(product.id)}><span className="entity-name"><i><Banknote size={17} /></i><span><strong>{product.name}</strong><small>{product.funder}</small></span></span><span>{product.audience}</span><span>{product.amountLabel}</span><span>{product.rateLabel}</span><span>{product.termLabel}</span><span>{product.currency}</span><span className="row-action">查看详情<ArrowRight size={14} /></span></button>)}</section> : <EmptyState title="未找到相关产品" description="请缩短关键词或尝试搜索资金方名称。" />}</div>;
}
